import type { Metadata } from "next";
import localFont from "next/font/local";
import { Inter } from "next/font/google";
import "./globals.css";

import NextAuthProvider from "@/app/providers";
import { getServerSession } from "next-auth/next";
import { nextAuthOptions } from "@/app/_utils/next-auth-optios";

// ローカルフォント
const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});

const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

// Googleフォント
const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

// RootLayoutコンポーネント
export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  // セッションを取得
  const session = await getServerSession(nextAuthOptions);

  return (
    <html lang="ja">
      <body
        className={`${geistSans.variable} ${geistMono.variable} ${inter.className} antialiased`}
      >
        <NextAuthProvider session={session}>
          {children}
        </NextAuthProvider>
      </body>
    </html>
  );
}
