import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "../globals.css";

import NextAuthProvider from "@/app/providers";
import { getServerSession } from "next-auth/next";

// import Header from "@/app/_components/header";
import { nextAuthOptions } from "@/app/_utils/next-auth-optios";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const session = await getServerSession(nextAuthOptions);

  return (
    <html lang="ja">
      <body className={inter.className}>
        <NextAuthProvider session={session}>
            {children}
        </NextAuthProvider>
      </body>
    </html>
  );
}